http:
  routers:
    app:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      service: app-weighted

  services:
    app-weighted:
      weighted:
        services:
          - name: app-stable@docker
            weight: 9
          - name: app-canary@docker
            weight: 1
